### ISSUE TITLE
Notice: Undefined property $cookieManager 

### ISSUE THREAD

**Issue by ktsixit** [mageplaza/magento-2-social-login#181]
### Preconditions
1. Magento: 2.2.6
2. PHP: 7.2

### Steps to reproduce
1. Login via Facebook

### Expected result
1. Redirect to Facebook and view login form

### Actual result
1. After making http request though `/lib/internal/Mageplaza/Facebook/Http/GraphRawResponse.php`
error message displays

```
Notice: Undefined property: Magento\\Framework\\App\\Http\\Context::$cookieManager in \/home\/mywebsite\/public_html\/vendor\/magento\/framework\/App\/Http\/Context.php on line 117",
#0 \/home\/mywebsite\/public_html\/vendor\/magento\/framework\/App\/Http\/Context.php(117): Magento\\Framework\\App\\ErrorHandler->handler(8, 'Undefined prope...', '\/home\/mywebsite\/publ...', 117, Array)\n
#1 \/home\/mywebsite\/public_html\/vendor\/magento\/framework\/App\/Response\/Http.php(102): Magento\\Framework\\App\\Http\\Context->getVaryString()\n
#2 \/home\/mywebsite\/public_html\/generated\/code\/Magento\/Framework\/App\/Response\/Http\/Interceptor.php(37): Magento\\Framework\\App\\Response\\Http->sendVary()\n
#3 \/home\/mywebsite\/public_html\/vendor\/magento\/module-page-cache\/Model\/App\/Response\/HttpPlugin.php(25): Magento\\Framework\\App\\Response\\Http\\Interceptor->sendVary()\n
#4 \/home\/mywebsite\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(121): Magento\\PageCache\\Model\\App\\Response\\HttpPlugin->beforeSendResponse(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n
#5 \/home\/mywebsite\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\Response\\Http\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n
#6 \/home\/mywebsite\/public_html\/generated\/code\/Magento\/Framework\/App\/Response\/Http\/Interceptor.php(117): Magento\\Framework\\App\\Response\\Http\\Interceptor->___callPlugins('sendResponse', Array, Array)\n
#7 \/home\/mywebsite\/public_html\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Response\\Http\\Interceptor->sendResponse()\n
#8 \/home\/mywebsite\/public_html\/index.php(44): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n
#9 {main}","url":"\/sociallogin\/social\/login\/type\/facebook\/","script_name":"\/index.php"}
```

**Comment by Victor-Mageplaza** [comment]
I see the above error is related to the context.
Please download the latest version of the module and try again.
Thank you!

**Comment by Victor-Mageplaza** [comment]
Due has passed a period of no response. I will close this topic here.
If you have the same problem, do not hesitate to reopen the topic.
Thank you!
