### ISSUE TITLE
Error While using Google Login

### ISSUE THREAD

**Issue by ideadx** [mageplaza/magento-2-social-login#9]
Hi, 

I am getting error when google auth comes back with user approval: 

`
a:4:{i:0;s:37:"Object DOMDocument should be created.";i:1;s:12647:"#0 /var/www/newproject/site/mage2/vendor/magento/framework/View/Element/UiComponent/Config/Reader.php(95): Magento\Framework\View\Element\UiComponent\Config\DomMerger->get$
#1 /var/www/newproject/site/mage2/vendor/magento/module-ui/Model/Manager.php(258): Magento\Framework\View\Element\UiComponent\Config\Reader->read()
#2 /var/www/newproject/site/mage2/vendor/magento/module-ui/Model/Manager.php(166): Magento\Ui\Model\Manager->prepare('customer_accoun...')
#3 /var/www/newproject/site/mage2/vendor/magento/framework/View/Element/UiComponentFactory.php(144): Magento\Ui\Model\Manager->prepareData('customer_accoun...')
#4 /var/www/newproject/site/mage2/vendor/magento/framework/View/Layout/Generator/UiComponent.php(124): Magento\Framework\View\Element\UiComponentFactory->create('customer_accoun...', NULL, Array)
#5 /var/www/newproject/site/mage2/vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'customer_a$
#6 /var/www/newproject/site/mage2/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View$
#7 /var/www/newproject/site/mage2/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Con$
#8 /var/www/newproject/site/mage2/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#9 /var/www/newproject/site/mage2/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#10 /var/www/newproject/site/mage2/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#11 /var/www/newproject/site/mage2/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#12 /var/www/newproject/site/mage2/vendor/magento/framework/View/Page/Config.php(197): Magento\Framework\View\Layout\Builder->build()
#13 /var/www/newproject/site/mage2/vendor/magento/framework/View/Page/Config.php(217): Magento\Framework\View\Page\Config->build()
`

Magento version: 2.0.3 on production mode
Php: 7 and Mysql
Plugin only using for Google Logins

Thanks for the plugin guys, please post the fix!

**Comment by ideadx** [comment]
And after this install, I can't see customers from my admin page as well!

**Comment by ideadx** [comment]
I think, what's happening is: if there is a admin user already in a system and then if you try to login with the same email using google + via plugin in, its getting crashed. 
just a guess!
